### ISSUE TITLE
ambiguous use of height - xcode 7.3

### ISSUE THREAD

**Issue by johndpope** [artman/Geometry#4]
This was working the other day in my project - but after a clean / and reloading of pods - compiler errors are persisting. It maybe safer to use viewHeight / viewWidth

<img width="1112" alt="screen shot 2016-06-06 at 8 36 24 am" src="https://cloud.githubusercontent.com/assets/289994/15808896/837dda04-2bc6-11e6-8a1b-5bf38d5a9147.png">

**Comment by sapzildj** [comment]
I also suffered from same error even if Xcode 8.1(swift3).
Now I 'm using fixed Geometry(https://github.com/artman/Geometry/pull/5/commits/93344d2b394faad366601e0cd400c237a7069e17).

@artman, 
Do you have any plan for this problem?
I sent PR. But closed TT(https://github.com/artman/Geometry/pull/5).

**Comment by artman** [comment]
Hi @sapzildj! What is this colliding with?

**Comment by sapzildj** [comment]
Hi, @artman .

CoreGraphics>CGGeometry>CGRect already has a width/height getter.

```swift
extension CGRect {
    public var width: CGFloat { get }
}
```

So, when I try to compile the project including Geometry, failed as below.

```
error: ambiguous use of 'width'

Geometry.CGRect:8:16: note: found this candidate
    public var width: CGFloat { get set }
               ^
CoreGraphics.CGRect:24:16: note: found this candidate
    public var width: CGFloat { get }
               ^
```

**Comment by artman** [comment]
Indeed, thanks. I'll remove width and height all together.

**Comment by sapzildj** [comment]
Then, I can contribute if you want!

**Comment by artman** [comment]
I've gut a PR up myself already, but thanks.

**Comment by artman** [comment]
And landed on master.
